spring:
  application:
    name: collector

kafka:
  topic.hub: telemetry.hubs.v1
  topic.sensor: telemetry.sensors.v1
  bootstrap.server: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

grpc.server.port: 9090
server.port: 8080